### PR TITLE
feat: change _getMappingForDestination to retrieve source type for ma…

### PR DESCRIPTION
**Pull request by vip30**
Change to use source object to determine which mapping will use

https://github.com/nartc/mapper/issues/47

### CODE REVIEW

**Comment by nartc** [comment]
@vip30 Thanks a lot for the PR. However, I have a couple of comments:
- Since now `_getMappingForDestination()` takes in the `source` object everywhere, can we modify `_getMappingForDestination()` to just respect the `SourceName` from `source` and DestinationName` from `destination` instead of trying to grab the `SourceName` from `DestinationMapping`? 
- Can you also add test cases and test for this PR?

Thanks again

**Comment by vip30** [comment]
Hi @nartc
Thanks for your review

For the test case, actually it fails the test after I modify the code thats why I grab the source key from destination again to fix the problem

And furthermore because you want to support the Json object(which the source obj is not a class) still need to have a work around to handle this case

**Comment by nartc** [comment]
> And furthermore because you want to support the Json object(which the source obj is not a class) still need to have a work around to handle this case
> (Either give the source class in options or just persist to use the first mapping)

I don't remember supporting plain JSON object because all mapping configurations are piped over `plainToClass` from `class-transformer`

**Comment by vip30** [comment]
Seems I misunderstanding the readme in 

https://github.com/nestjsx/automapper/blob/master/README.md

i.e.
...
const result = await newUser.save();
return this._mapper.map(result.toJSON(), UserVm);
...

**Comment by nartc** [comment]
@vip30 the README example uses `mongoose` as an example which is probably be a bad example. I'll get that cleaned up. However, we can always add overloads to the `map` methods to take in a `SourceType` instead of trying to "guess". 

In other note, check out this commit: https://github.com/nartc/mapper/commit/cd6cdd1a89a99fb805832dbc7a2fc7fc5def1182 and let me know what you think.

**Comment by vip30** [comment]
Yes It is better that if we can pass the source type so plain js object can be mapped too

For the commit
I just think decorator should use PascalCase rather than CamelCase


`autoMap` to `AutoMap`

**Pull request closed without merging**
