### PR TITLE
feat(nestjs): support NestJs 9.0.0

### LINKED ISSUE #488: Support NestJs ^9.0.0
### Is your feature request related to a problem? Please describe.

We want to upgrade nestJs to version 9. However, since automapper requires the peer dependency `@nestjs/common@"^7.0.0 || ^8.0.0"` NPM complains.

### Describe the solution you'd like

Support also the peer dependency `@nestjs/common@"^7.0.0 || ^8.0.0" || "^9.0.0"`.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by HaaLeo**
Closes #488

### CODE REVIEW

**Comment by HaaLeo** [comment]
How can I update the `pnpm-lock`? When I ran `npm i` only the `package-lock.json` was generated. I also was wondering why the package-lock.json was not committed.

**Comment by nartc** [comment]
@HaaLeo the repo is using `pnpm` so you might want to get `pnpm` setup. Are you able to do that? I can take over the PR if you're not able to proceed with `pnpm`

**Comment by HaaLeo** [comment]
Feel free to take over from here :)

**Comment by VPecquerie** [comment]
@nartc, check this PR with pnpm update: https://github.com/nartc/mapper/pull/494

**Pull request closed without merging**
