### PR TITLE
feat: use array to store paths

### PR DESCRIPTION
**Pull request by AliYusuf95**
Solve #299

### CODE REVIEW

**Comment by AliYusuf95** [comment]
@nartc I have a note about this line:

https://github.com/nartc/mapper/blob/f7e89d6228215bd77ce2dea2caf166187fa012a3/packages/core/src/lib/map/map.ts#L226

Is it on purpose to start in reverse order? I assumed that `forMemer` should overwrite the default mapping so I change it to the normal order in the PR. 😅

**Comment by nartc** [comment]
> @nartc I have a note about this line:
> 
> https://github.com/nartc/mapper/blob/f7e89d6228215bd77ce2dea2caf166187fa012a3/packages/core/src/lib/map/map.ts#L226
> 
> Is it on purpose to start in reverse order? I assumed that `forMemer` should overwrite the default mapping so I change it to the normal order in the PR. 😅

It is. Because in initializeMapping, I do start in `reverse`. `forMember` does override default mapping. The only affect it would have is the order of the mapped result. We can double check in the tests.

**Comment by AliYusuf95** [comment]
> It is. Because in initializeMapping, I do start in `reverse`. `forMember` does override default mapping. The only affect it would have is the order of the mapped result. We can double check in the tests.

It's true that `initializeMapping` adds mappings in reverse order, also `createMapForMember` overrides the mapping for exists properties. However, if the property not in the source, then `createMapForMember` pushes the override property to the end. 
https://github.com/nartc/mapper/blob/f7e89d6228215bd77ce2dea2caf166187fa012a3/packages/core/src/lib/create-mapper/create-map-for-member.util.ts#L80

My expectation was that when I use `forMember` in the parent class, this should override the result for the inner properties. That's why I changed the loop to the normal order.

```ts
// example test
export const deepNestedFooFooFooProfile: MappingProfile = (mapper) => {
  mapper.createMap(FooFooFoo, FooFooFooDto).forMember(
    (dest) => dest.foo,
    fromValue('FooFooFoo Custom Value')
  );
  mapper.createMap(FooFoo, FooFooDto).forMember(
    (dest) => dest.foo.foo,
    fromValue('FooFoo Custom Value')
  );
  mapper.createMap(Foo, FooDto).forMember(
    (dest) => dest.foo.foo.foo,
    fromValue('Foo Custom Value')
  );
};

// Succeed
    it('should map forMember override properly', () => {
      mapper.addProfile(deepNestedFooFooFooProfile);

      const foo = new FooFooFoo();
      foo.foo = 'some value';

      const vm = mapper.map(foo, FooFooFooDto, FooFooFoo);
      expect(vm).toBeTruthy();
      expect(vm.foo).toEqual('FooFooFoo Custom Value');
    });

// Failed
    it('should map inner forMember override properly', () => {
      mapper.addProfile(deepNestedFooFooFooProfile);

      const foo = new FooFoo();
      foo.foo = new FooFooFoo();
      foo.foo.foo = 'some value';

      const vm = mapper.map(foo, FooFooDto, FooFoo);
      expect(vm).toBeTruthy();
      expect(vm.foo.foo).toEqual('FooFoo Custom Value');  // <= Received: "FooFooFoo Custom Value"
    });

// Failed
    it('should map deep inner forMember override properly', () => {
      mapper.addProfile(deepNestedFooFooFooProfile);

      const vm = mapper.map({ foo: {foo: { foo: 'some value' }} }, FooDto, Foo);
      expect(vm).toBeTruthy();
      expect(vm.foo.foo.foo).toEqual('Foo Custom Value'); // <= Received: "FooFooFoo Custom Value"
    });

```

I'm not sure if this behavior is intended or not, but in the previous version, I was able to override the inner properties.

**Comment by nartc** [comment]
That is definitely a bug imho. If we change from `mapping[MappingClassId.properties].push([memberPath, mappingProperty]);` to `mapping[MappingClassId.properties].unshift([memberPath, mappingProperty]);`, what do you think? performance wise? If anything, I'd prefer to make the code of mapping configurations (that likely to run once, like `forMember()`) less performant than to make the code that `map()`.

**Comment by AliYusuf95** [comment]
It could be `unshift`, as you said more likely it'll run only once. But I get the point of the process:
- Adding initial properties in reversed order to the map
- `unshift` new properties
- Start the mapping in the reversed order

It could be just the normal order with `push` in this case.

**Comment by nartc** [comment]
I’m fine with push + normal order as well. We can go with that.

**Comment by AliYusuf95** [comment]
I have changed other reversed loops to normal loops 👍

**Comment by nartc** [comment]
Thanks man. I'll be reviewing this today!

**Review by nartc — APPROVED** [review]
Thanks a lot for the PR. LGTM. It actually cleans up quite a bit.

**Pull request merged**
