### PR TITLE
fix(classes): fix main (i.e. ".") export of package.json

### PR DESCRIPTION
**Pull request by gabrielkim13**
ISSUES CLOSED: #587

I've simply replaced "./" with "." in the main export of `@automapper/classes`'s `package.json`.

### CODE REVIEW

**Comment by gabrielkim13** [comment]
> lol i made the same fix as you :P

Glad to see I'm not the only one interested on this fix :)

**Comment by Luedan** [comment]
so many ppl w8 for this uptade :(

**Comment by dtap001** [comment]
@gabrielkim13 approved, lets merge!

**Comment by nartc** [comment]
I merged @dtap001 PR instead with the same change (also cut a quick release)

**Pull request closed without merging**
